### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by LordPhobos** [lavigor/notifications#6]
Hi.

I am **really** interested in this extension, but it won't install on my board located on https://www.anonimagiocatori.it/forum, always saying some requirements (unspecified) are missing.

To be compliant with this extension, I upgraded my php to 7.1 version, forced secure cookie and now I use https, and asked my provider if I have OpenSSL and GMP extension enabled: they say "yes".

Could you please help me?

Thanks in advance

**Comment by lavigor** [comment]
Hello,

Please make sure that you download the proper version of the extension for your phpBB version (3.1 or 3.2).
Then check whether PHP extensions are actually enabled on PHP information page in the ACP of your board.

If this doesn't help, please PM me (on phpbb.com) admin access to your board so that I can check what's going on.

Best regards,
Igor

**Comment by LordPhobos** [comment]
I PMed you.

**Comment by Scorpions95** [comment]
hi there
when i try to instal push notification ext
i see this issue
http://test.kefcheto.eu/ext/dmzx/imageupload/files/2327c21b057fa93b2bb0c923989cb02f.png
i test is on my test board here http://test.kefcheto.eu

**Comment by lavigor** [comment]
@Scorpions95 'this issue' confirms that you have not met the installation requirements mentioned in extension's Readme file and on its website.

**Comment by Scorpions95** [comment]
https://rocknmetalbulgaria.eu/ext/dmzx/imageupload/files/b5cda53ae77841fc24a726d3404bce3d.png this is my PHPBB version

https://rocknmetalbulgaria.eu/ext/dmzx/imageupload/files/e81ccabd7b3d9dfef21c5d4c92cf4ffb.png this is my php version 
what i need to update?

**Comment by lavigor** [comment]
@Scorpions95 please verify extension's requirements.
PHP GMP and OpenSSL extensions are mandatory for its work.

**Comment by Scorpions95** [comment]
i update my php and phpbb versions 
My PHP version: https://rocknmetalbulgaria.eu/ext/dmzx/imageupload/files/d63aa7ab5cf103fb025dfbad30d5b67c.png

My PHPBB version: https://rocknmetalbulgaria.eu/ext/dmzx/imageupload/files/267ba5d5769607a37aaa7f86c8a4223e.png

```
Requirements
* phpBB 3.2.0 or higher
* PHP 7.0 or higher
* PHP extensions enabled: [GMP](http://php.net/manual/en/book.gmp.php) and [OpenSSL](http://php.net/manual/en/book.openssl.php)
* HTTPS enabled
```

**Comment by Scorpions95** [comment]
i change my php version on 7.1 and i can't still enable it

**Comment by lavigor** [comment]
@Scorpions95 please check the GMP extension of PHP.
It should be enabled if you want to use this phpBB extension.
Your PHP and phpBB versions were absolutely OK from the very beginning.

**Comment by Scorpions95** [comment]
Where  i can find GMP to check it?

**Comment by lavigor** [comment]
@Scorpions95 on the same page with PHP information.
If you cannot find it there, it is disabled.

**Comment by lavigor** [comment]
By the way, the original issue was also about GMP extension support.
I'll probably add some language variables later in order to specify the reason when this extension cannot be enabled on the board.

There's no issue in the extension itself so I'm closing this one.

@Scorpions95 please use your own issue #7 if you have any further questions.
