### ISSUE TITLE
Extension not showing up on 3.2.2

### ISSUE THREAD

**Issue by AlexHowser** [lavigor/notifications#9]
Hey!
I downloaded the package, placed it in the ext folder, extracted it, but it is not shown in the extensions in acc? Is the package compatible with 3,.2.2?
Alex

**Comment by lavigor** [comment]
@AlexHowser absolutely.

Please, just please look carefully at the instructions how to install phpBB extensions.
There is also a helpful tool ([Upload Extensions](https://github.com/BoardTools/upload)) that simplifies the installation process so that you won't need to adjust the installation path for each extension.
You will only need to do it once (again, please study the Readme and instructions).

Best regards,
Igor

**Comment by AlexHowser** [comment]
thx @lavigor !sorry,  i read over the upload extension part, cause it worked with the manual method so far. Thx for the quick reply! good job man!
